// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqTfYuDThUvvshBn2_VZx8d0J45HNnEAc',
    appId: '1:225255576154:web:7f03d5ded0d518d839be63',
    messagingSenderId: '225255576154',
    projectId: 'persona-753f1',
    authDomain: 'persona-753f1.firebaseapp.com',
    storageBucket: 'persona-753f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8F5i6CeUjZBgDDWlpbIvcgP8xC5SXBs',
    appId: '1:225255576154:android:48b1b41402b3570b39be63',
    messagingSenderId: '225255576154',
    projectId: 'persona-753f1',
    storageBucket: 'persona-753f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwOIHQ80pcAfknOEpIAT0peesbwqCmQI',
    appId: '1:225255576154:ios:2502750701ca06be39be63',
    messagingSenderId: '225255576154',
    projectId: 'persona-753f1',
    storageBucket: 'persona-753f1.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwOIHQ80pcAfknOEpIAT0peesbwqCmQI',
    appId: '1:225255576154:ios:b2c233e69f5a66b339be63',
    messagingSenderId: '225255576154',
    projectId: 'persona-753f1',
    storageBucket: 'persona-753f1.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
